import React from 'react'

const PostsList = () => {
  return (
    <>
    <div style={{
      // overflowY:'auto',
      // height:'100vh',
      // width:'80vw',
    }}>
      
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div></div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    <div>PostsLIst</div>
    </div>
    </>
  )
}

export default PostsList